# -*- coding: utf-8 -*-
"""mapacuritiba2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bedacUlMNdsDj1rdobA14vtCkuVsnZ3G
"""


import streamlit as st
import folium
from streamlit_folium import st_folium

# Título da aplicação Streamlit
st.title("Mapa de Curitiba")

# --- Definir as coordenadas do centro de Curitiba ---
curitiba_latitude = -25.43
curitiba_longitude = -49.27

# --- Criar o mapa Leaflet usando Folium ---
m = folium.Map(location=[curitiba_latitude, curitiba_longitude], zoom_start=12)

# --- Adicionar um marcador no centro de Curitiba (opcional) ---
folium.Marker([curitiba_latitude, curitiba_longitude], popup="Centro de Curitiba").add_to(m)

# --- Exibir o mapa no Streamlit ---
st_folium(m, width=700, height=500)


m
