# -*- coding: utf-8 -*-
"""Cópia de meuaplicativo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CfMtOJXu4rtD-NAEuhbefQZrPiYjff4M
"""

import streamlit as st
from streamlit_folium import folium_static
import folium

PAGE_CONFIG = {"page_title":"Aplicação de Mapas","page_icon":":smiley:","layout":"centered"}
st.set_page_config(**PAGE_CONFIG)

def main():
	st.title("Como adicionar mapas no StreamLit")
	st.subheader("Baseado num caderno do Colab")
	menu = ["Home","Mapa"]