# -*- coding: utf-8 -*-
"""teste5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PIlJ7TmpLkkedJMcyatDuoB0w4Aiz2Yl
"""

!pip install streamlit

import streamlit as st

PAGE_CONFIG = {"page_title":"Aplicação de Mapas","page_icon":":smiley:","layout":"centered"}
st.set_page_config(**PAGE_CONFIG)

def main():
	st.title("Como adicionar mapas no StreamLit")
	st.subheader("Baseado num caderno do Colab")